default-channels = ["conda-forge"]

[mirrors]
# https://pixi.sh/dev/reference/pixi_configuration/
# redirect all requests for conda-forge to the prefix.dev mirror
"https://conda.anaconda.org/conda-forge" = [
    # "https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud",
    "https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge",
    "https://prefix.dev/conda-forge",
]
"https://conda.anaconda.org/conda-forge/label" = [
    "https://conda.anaconda.org/conda-forge/label",
]
"https://pypi.org/simple" = [
    "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple",
]

[pypi-config]
# Main index url
# index-url = "https://pypi.org/simple"
index-url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"
